"""add preferences table

Revision ID: 386bfa5be3a3
Revises: 3211f2f5bb13
Create Date: 2026-08-04 14:09:55.795691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '386bfa5be3a3'
down_revision: Union[str, Sequence[str], None] = '3211f2f5bb13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preferences',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preferences_user_id'), 'preferences', ['user_id'], unique=False)
    op.drop_table('agents')
    # 旧 schema 的 users 只有 role_id(见 3211f2f5bb13),role_code 并不存在,
    # 这里补上新模型需要的 role_code 列,并移除已废弃的 role_id。
    op.add_column('users', sa.Column('role_code', sa.String(length=32), nullable=True))
    op.drop_index('ix_users_role_id', table_name='users')
    op.drop_column('users', 'role_id')
    # 统一审批中心(Approval)合并了旧 HitlTask + ExperienceApproval,清掉旧表
    op.drop_table('hitl_tasks')
    op.drop_table('experience_approvals')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experience_approvals',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('experience_id', sa.String(length=36), nullable=False),
    sa.Column('from_scope', sa.String(length=16), nullable=False),
    sa.Column('to_scope', sa.String(length=16), nullable=False),
    sa.Column('approver_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experience_approvals_experience_id'), 'experience_approvals', ['experience_id'], unique=False)
    op.create_index(op.f('ix_experience_approvals_approver_id'), 'experience_approvals', ['approver_id'], unique=False)
    op.create_table('hitl_tasks',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('trace_id', sa.String(length=36), nullable=False),
    sa.Column('node_id', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('approver_id', sa.String(length=36), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hitl_tasks_approver_id'), 'hitl_tasks', ['approver_id'], unique=False)
    op.create_index(op.f('ix_hitl_tasks_trace_id'), 'hitl_tasks', ['trace_id'], unique=False)
    op.add_column('users', sa.Column('role_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.drop_column('users', 'role_code')
    op.create_table('agents',
    sa.Column('code', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('model_key', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('agents_pkey'))
    )
    op.drop_index(op.f('ix_preferences_user_id'), table_name='preferences')
    op.drop_table('preferences')
    # ### end Alembic commands ###
