"""add default_risk to mcp_servers

Revision ID: 875bb3f2fca0
Revises: 91ed1ecb1d5e
Create Date: 2026-08-05 14:35:17.617053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '875bb3f2fca0'
down_revision: Union[str, Sequence[str], None] = '91ed1ecb1d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_mcp_bindings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_code', sa.String(length=32), nullable=False),
    sa.Column('mcp_server_name', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_mcp_bindings_agent_code'), 'agent_mcp_bindings', ['agent_code'], unique=False)
    op.add_column('mcp_servers', sa.Column('default_risk', sa.String(length=16), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mcp_servers', 'default_risk')
    op.drop_index(op.f('ix_agent_mcp_bindings_agent_code'), table_name='agent_mcp_bindings')
    op.drop_table('agent_mcp_bindings')
    # ### end Alembic commands ###
