"""add approval table

Revision ID: 91ed1ecb1d5e
Revises: 386bfa5be3a3
Create Date: 2026-08-04 16:37:52.164220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91ed1ecb1d5e'
down_revision: Union[str, Sequence[str], None] = '386bfa5be3a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvals',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('risk', sa.String(length=16), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('ref_type', sa.String(length=32), nullable=False),
    sa.Column('ref_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('requester_id', sa.String(length=36), nullable=False),
    sa.Column('approver_id', sa.String(length=36), nullable=True),
    sa.Column('approver_role', sa.String(length=32), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_approver_id'), 'approvals', ['approver_id'], unique=False)
    op.create_index(op.f('ix_approvals_category'), 'approvals', ['category'], unique=False)
    op.create_index(op.f('ix_approvals_ref_id'), 'approvals', ['ref_id'], unique=False)
    op.create_index(op.f('ix_approvals_requester_id'), 'approvals', ['requester_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approvals_requester_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_ref_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_category'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_approver_id'), table_name='approvals')
    op.drop_table('approvals')
    # ### end Alembic commands ###
