"""dingtalk org sync fields

Revision ID: a78712a6db47
Revises: 4eef8f120f75
Create Date: 2026-08-12 15:52:51.595411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a78712a6db47'
down_revision: Union[str, Sequence[str], None] = '4eef8f120f75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_binding',
    sa.Column('approval_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('process_code', sa.String(length=64), nullable=False),
    sa.Column('process_instance_id', sa.String(length=64), nullable=False),
    sa.Column('pushed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pushed', nullable=False),
    sa.PrimaryKeyConstraint('approval_id'),
    sa.UniqueConstraint('process_instance_id')
    )
    op.create_table('dingtalk_sync_state',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sync_type', sa.String(length=32), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cursor', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sync_type')
    )
    # 注意：checkpoint_migrations/checkpoints/checkpoint_writes/checkpoint_blobs 四张表
    # 由 langgraph-checkpoint-postgres 运行时自动创建，不在 SQLAlchemy metadata 中。
    # autogenerate 曾误判它们为「多余表」生成 drop，这里必须手工剔除——
    # 否则升级会删掉 LangGraph 检查点数据（会话断点 / 审批 interrupt 状态全部丢失）。
    op.add_column('departments', sa.Column('parent_id', sa.String(length=36), nullable=True))
    op.add_column('departments', sa.Column('dingtalk_dept_id', sa.BigInteger(), nullable=True))
    op.add_column('departments', sa.Column('source', sa.String(length=16), server_default='manual', nullable=False))
    op.add_column('departments', sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('departments_name_key'), 'departments', type_='unique')
    op.create_index(op.f('ix_departments_parent_id'), 'departments', ['parent_id'], unique=False)
    op.create_unique_constraint('uq_departments_parent_name', 'departments', ['parent_id', 'name'])
    op.create_unique_constraint('uq_departments_dingtalk_dept_id', 'departments', ['dingtalk_dept_id'])
    op.add_column('users', sa.Column('dingtalk_userid', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('mobile', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('avatar', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('job_number', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('title', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('status', sa.String(length=16), server_default='active', nullable=False))
    op.add_column('users', sa.Column('source', sa.String(length=16), server_default='manual', nullable=False))
    op.add_column('users', sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint('uq_users_dingtalk_userid', 'users', ['dingtalk_userid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_dingtalk_userid', 'users', type_='unique')
    op.drop_column('users', 'synced_at')
    op.drop_column('users', 'source')
    op.drop_column('users', 'status')
    op.drop_column('users', 'title')
    op.drop_column('users', 'job_number')
    op.drop_column('users', 'avatar')
    op.drop_column('users', 'email')
    op.drop_column('users', 'mobile')
    op.drop_column('users', 'dingtalk_userid')
    op.drop_constraint('uq_departments_dingtalk_dept_id', 'departments', type_='unique')
    op.drop_constraint('uq_departments_parent_name', 'departments', type_='unique')
    op.drop_index(op.f('ix_departments_parent_id'), table_name='departments')
    op.create_unique_constraint(op.f('departments_name_key'), 'departments', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('departments', 'synced_at')
    op.drop_column('departments', 'source')
    op.drop_column('departments', 'dingtalk_dept_id')
    op.drop_column('departments', 'parent_id')
    op.drop_table('dingtalk_sync_state')
    op.drop_table('approval_binding')
    # ### end Alembic commands ###
