"""add seq to messages

Revision ID: e81875a7d0b7
Revises: 875bb3f2fca0
Create Date: 2026-08-05 15:42:57.110317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e81875a7d0b7'
down_revision: Union[str, Sequence[str], None] = '875bb3f2fca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('seq', sa.Integer(), sa.Identity(always=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'seq')
    # ### end Alembic commands ###
